### PR TITLE
feat: add options.locale

### PR DESCRIPTION
**Pull request by revolunet**
Adds the ability to set playwright `locale`

https://playwright.dev/docs/api/class-testoptions#test-options-locale

### CODE REVIEW

**Comment by andrewbrey** [comment]
@revolunet Thank you for the contribution! On quick inspection this looks great, but I am afk for another couple days, and don't want to merge before I have a chance to sit back at my computer and look more thoroughly. I'll get back to you in a couple days - cheers!

**Comment by revolunet** [comment]
no hurry @andrewbrey , enjoy your days afk :)

**Comment by MattiSG** [comment]
We @OpenTermsArchive are very excited about this feature landing in [Dashlord](https://github.com/socialgouv/dashlord), one of the tools we use and that relies on this component 🙂 Thanks @revolunet for suggesting its addition!

cc @clementbiron

**Comment by andrewbrey** [comment]
@revolunet LGTM, thanks for the PR :+1:

**Comment by revolunet** [comment]
thanks @andrewbrey for pwpr 🙌

**Comment by revolunet** [comment]
Looks like something is not working correctly for some reason 🤔  :

`npx pwpr --url https://opentermsarchive.org --locale fr-FR  | grep -o "Access\w*"`  gives `Accessibility`
while
`node bin/run --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"` gives `Accessibilité`

**Comment by andrewbrey** [comment]
`npx` caches modules that you run with it, so I would bet that's what's going on here. Try purging your `npx` cache and retrying because it looks like it's running an older version of the module. There may also be a flag for it to tell it to refresh the module before running, but I'm not sure on that.

**Comment by revolunet** [comment]
for some reason looks like theres an issue with the release; try with : `npx pwpr --url https://opentermsarchive.org`

**Comment by andrewbrey** [comment]
@revolunet Could you please confirm you have purged your npx cache?

**Comment by andrewbrey** [comment]
@revolunet I just did a test of this on my own machine, and after ensuring that my `npx` cache was purged (to ensure `npx` used the latest version of the module), I observed the desired behavior:

image


So, again, I believe that the reason this isn't working for you is due to `npx` module caching. I'll also mention that with `npx` you can always pin a specific version for the module, and doing that also reveals the change in behavior:

image

**Comment by revolunet** [comment]
Hello,
It now works locally thank you
I'm trying to run pwpr in a github action but for some reason it fails 

Here's the workflow : https://github.com/revolunet/test-actions/blob/master/.github/workflows/pwpr.yml

And it only works with pwpr@2.2.0, version >=3 fails with the same error as locally previously

Capture d’écran 2022-06-29 à 10 22 15

Capture d’écran 2022-06-29 à 10 22 22

**Comment by andrewbrey** [comment]
@revolunet I _think_ the solution should just be adding a step to your github action workflow to follow the instructions printed by `playwright` there which will ensure that the browser is installed. I believe you should also be able to limit the `playwright install` to just include `chrome` (or just firefox / webkit) which will be useful since `pwpr` uses chromium only :+1:

**Comment by revolunet** [comment]
Hello, yep, thats one of the test in the workflow and for some reason it fails with latest 🤔 tested with node 14 and 16

**Pull request merged**
